name: Deployment From Github To AWS
on:
  push:
    branches:
      - beanstalk-deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master
        
      - name: Generate Deployment Package 
        run: zip -r deploy.zip * -x "**node_modules**"
          
      -- name: Beanstalk Deploy
  uses: einaregilsson/beanstalk-deploy@v20
 
#       name: Deploy to EB
#         uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Warehouse-Deployment
          environment_name: Warehousedeployment-env
          version_label: 12345
          aws-region: us-east-1
          deployment_package: deploy.zip
          
     
